version: '3.8'

services:
  directus:
    image: directus/directus:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_HTTP_PORT}:8055
    volumes:
      - directus:/directus
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'pg'
      DB_HOST: ${APP_CONTAINER_NAME}-postgres
      DB_PORT: '5432'
      DB_DATABASE: ${DB_POSTGRE_NAME}
      DB_USER: ${DB_POSTGRE_USER}
      DB_PASSWORD: ${DB_POSTGRE_PASSWORD}

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ${EMAIL}
      ADMIN_PASSWORD: ${APP_PASSWORD}

      # Make sure to set this in production
      # (see https://docs.directus.io/reference/environment-variables/#general)
      # PUBLIC_URL: 'https://directus.example.com'

    depends_on:
      - cache
      - db
    links: 
      - db
      - cache
    restart: on-failure:3

  db:
    image: postgres:${DB_POSTGRE_VERSION}
    container_name: ${APP_CONTAINER_NAME}-postgres
    restart: on-failure:3
    volumes:
      - ${VOLUMES_PATH_PREFIX}/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRE_DB: ${DB_POSTGRE_NAME}
      POSTGRE_USER: ${DB_POSTGRE_USER}
      POSTGRE_PASSWORD: ${DB_POSTGRE_PASSWORD}

  cache:
    image: redis:${DB_REDIS_VERSION}
    container_name: ${APP_CONTAINER_NAME}-redis

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  directus:
